### ISSUE TITLE
发现错误  "公有链在共识机制的选择上一般都会采用拜占庭容错机制"，"公有链‘’应为 联盟链

### ISSUE THREAD

**Issue by Jack0Fu** [yingpingzhang/enterprise_blockchain_tutorial#2]
在文件 enterprise_blockchain_tutorial/chapter1_02 types_ of_blockchains.md
区块链的分类 这一节的中间部分，描述联盟链时有出错, **"公有链‘’应为 联盟链**
"公有链在共识机制的选择上一般都会采用拜占庭容错机制，拜占庭机制解决了节点故障和节点作恶（伪造数据）情况下，系统都能够达成共识。由于联盟链节点数有限且需要认证，为了提高效率，因此大部分联盟链在共识机制上弱化了节点作恶，重点考虑系统1/3节点故障下系统共识机制的达成。"

**Comment by yingpingzhang** [comment]
这个描述没有问题。
公有链的共识机制强度要高于联盟连。联盟链由于节点需要认证，弱化了共识机制。

**Comment by Jack0Fu** [comment]
“使用拜占庭容错算法不需要发行加密货币，但是只能用于私有链或者联盟链，需要对节点的加入进行权限控制；不能用于公有链，因为公有链中所有节点都可以随意加入退出，无法抵挡女巫攻击（sybil attack）。” 公有链一般是采用POW和POS等吧，目前很少看到公有链在用PBFT的，像fabric这种联盟链采用PBFT。不知道我的理解对不对。

**Comment by yingpingzhang** [comment]
PoW和PoS都属于拜占庭共识机制，是目前公链采用最多的。PBFT（Practical Byzantine Fault Tolerance）简易拜占庭是部分联盟链采用的共识机制，但由于效率比较低下，所以目前主流联盟链采用非拜占庭共识机制居多。
